version: '2'
services:
  runeman-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/runeMan/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=runeMan
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
